CREATE TABLE ACCOUNTS (
  USERID VARCHAR(10) PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(10) NOT NULL,
  MAILADDRESS VARCHAR(100) NOT NULL,
  AGE INT NOT NULL
);

CREATE TABLE MUTTERS (
  MUTTERID INT AUTO_INCREMENT PRIMARY KEY,
  TEXT VARCHAR(140) NOT NULL,
  USERID VARCHAR(10) NOT NULL,
  FOREIGN KEY (USERID) REFERENCES ACCOUNTS(USERID)
);